### ISSUE TITLE
New account faucet redirect should be optional when wallet contains other accounts with balances

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/web_wallet#513]
I have some accounts with funds in my wallet already.  I want to register a new account.

It redirects me to the faucet page even though I selected an existing account to pay from.

I should be able to pay from an existing account without going through the faucet, if I already have an account with a non-zero balance in the wallet.

**Comment by theoreticalbts** [comment]
Update:  I am being redirected to the faucet even when I gave the new account a 1 BTS balance (from the command line on another client).

I think this makes the web wallet effectively useless for non-faucet account registrations.

**Comment by valzav** [comment]
I think this is a bug, I'll take a look..

**Comment by valzav** [comment]
Fixed. I think we need to issue GUI update.

**Comment by jcalfee** [comment]
Nope, not fixed.  Only option is the faucet registration even though I have a balance in the account.
